version: "3.7"

services:
  de_mysql:
    image: mysql:8.0
    container_name: de_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - de_network
  de_psql:
    image: postgres:15
    container_name: de_psql
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - de_network

  minio:
    hostname: minio
    image: "minio/minio"
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: ["server","/data","--console-address",":9001"]
    volumes:
      - ./minio:/data

    env_file:
      - .env
    networks:
      - de_network


  jupyter_notebook:
    image: jupyter_notebook
    build:
      dockerfile: ./Dockerfile
    container_name: "jupyter_notebook"
    user: root
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - de_network
networks:
  de_network:
    driver: bridge
    name: de_network
